#!/bin/bash 

if [[ -f Dockerfile ]]; then

  file="config"
  while read -r line; do
      language="$line"
  done < "$file"

  if [ "$( podman ps -a | grep -c "${language}-proj" )" -gt 0 ]; then
    echo "removing ..."
    #these two lines of code will remove the code folder (USE with CAUTION)
    #uncommenting them can result of you losing your code on ./clean
    #docker start ${language}-proj
    #docker exec ${language}-proj rm -rf $language
    podman stop "${language}-proj" && podman rm "${language}-proj" 
  else
    echo "No docker containers"
  fi

  if [ "$( podman images | grep -c "${language}-sandbox" )" -gt 0 ]; then
    podman rmi "${language}-sandbox"
  else
    echo "No docker images"
  fi


  rm config
  rm Dockerfile

else
  echo 'Nothing to clean'
fi
