#!/bin/bash 

main() {

if [[ -z "$1"  ]]; then echo 'Specify language'
else
  language="$1"

  case $language in 

  go)
    setup "golang" "go"
  ;;

  js)
    setup "node:latest" "js"
  ;;

  kt)
    setup "zenika/kotlin" "kt"
  ;;

  ktg)
    setup "gradle" "ktg"
  ;;

  java)
    setup "openjdk:latest" "java"
  ;;

  javag)
    setup "gradle" "javag"
  ;;

  py) 
    setup "python:3.9" "python"
  ;;

  rust)
    setup "rust" "rust"
  ;;

  jsdeno) 
    setup "denoland/deno" "deno"
  ;;

  *) 
  exit
  ;;

esac


fi

}


setup () {

  dockerimage=$1
  language=$2
  rm Dockerfile
  touch Dockerfile
  echo "FROM docker.io/${dockerimage}" >> Dockerfile
  echo "WORKDIR /code" >> Dockerfile

  copyfiles ${language}
  
  docker build -t "${language}-sandbox" .
  docker run --name "${language}-proj" -e "containername=${language}-proj" -it -v "$(pwd):/code" "${language}-sandbox" bash

  touch config
  echo ${language} > config
}

copyfiles () {
  (
    language=$1
    mkdir ${language}
    cd ${language} || exit
    git clone https://github.com/mskramst/scaffold.git
    cd scaffold/${language} || exit
    cp -r src ../../
    cp ./* -r ../../
  )
  (
  cd ../..
  rm -rf scaffold
  )
}

main "$@"
