#!/bin/bash 

main() {

if [[ -z "$1"  ]]; then echo 'Specify language'
else
  language="$1"

  case $language in 

  go)
  dockerimage="golang"
  language="go"
  ;;

  js)
  dockerimage="node:latest"
  language="js"
  ;;

  kt)
  dockerimage="zenika/kotlin"
  language="kt"
  ;;

  java)
  dockerimage="openjdk:latest"
  language="java"
  ;;

  py) 
  dockerimage="python:3.9"
  language="python"
  ;;

esac

  rm Dockerfile
  touch Dockerfile
  echo "FROM ${dockerimage}" >> Dockerfile
  echo "WORKDIR /code" >> Dockerfile

  copyfiles
  
  docker build -t "${language}-sandbox" .
  docker run --name "${language}-proj" -e "containername=${language}-proj" -it -v "$(pwd):/code" "${language}-sandbox" bash

  touch config
  echo ${language} > config

fi

}

copyfiles() {
  (
    mkdir ${language}
    cd ${language} || exit
    git clone https://github.com/mskramst/scaffold.git
    cd scaffold/${language} || exit
    cp -r src ../../
    cp ./* -r ../../
  )
  (
  cd ../..
  rm -rf scaffold
  )
}

main "$@"
