  services:
        adminer:
            image: dockette/adminer:full-php5
            restart: always
            ports:
                - 8080:8080
        dbPostgres:
            image: postgres:10
            restart: always
            ports:
                - 5432:5432
            environment:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: ppass 
                POSTGRES_DB: mydb
        dbMysql:
            image: mysql:8.0.3
            restart: always
            ports:
                - 3306:3306
            environment:
                MYSQL_ROOT_PASSWORD: mpass 
                MYSQL_DATABASE: mydb
        dbMongo:
            image: mongo:3.6.2
            restart: always
            ports:
                - 27017:27017
            environment:
                MONGO_INITDB_ROOT_USERNAME: root
                MONGO_INITDB_ROOT_PASSWORD: dpass 
